name: GitHub Action for Firebase

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: matt-dumler-pwa
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

