name: GitHub Action for Firebase

on:
  push:
    branches: 
      - master

env:
  PROJECT_ID: matt-dumler-pwa
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting --project $PROJECT_ID --token $FIREBASE_TOKEN

